# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge on Join statements.

## Objectives

You will be able to:
- Write queries that make use of various types of Joins
- Join tables using foreign keys

## CRM Schema

In almost all cases, rather then just working with a single table we will typically need data from multiple tables. 
Doing this requires the use of **joins ** using shared columns from the two tables. 

In this lab, we'll use the same Customer Relationship Management (CRM) database we used in our lecture before!
<img src='Database-Schema.png' width=550>

## Connecting to the Database
Import the necessary packages and connect to the database **data.sqlite**.

In [1]:
#Your code here
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

## Display the names of all the employees in Boston.

In [2]:
#Your code here
cur.execute('''SELECT firstname, lastname FROM offices JOIN employees WHERE city = "Boston" ''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df

   firstName   lastName
0      Diane     Murphy
1       Mary  Patterson
2       Jeff   Firrelli
3    William  Patterson
4     Gerard     Bondur
5    Anthony        Bow
6     Leslie   Jennings
7     Leslie   Thompson
8      Julie   Firrelli
9      Steve  Patterson
10  Foon Yue      Tseng
11    George     Vanauf
12      Loui     Bondur
13    Gerard  Hernandez
14    Pamela   Castillo
15     Larry       Bott
16     Barry      Jones
17      Andy     Fixter
18     Peter      Marsh
19       Tom       King
20      Mami      Nishi
21   Yoshimi       Kato
22    Martin     Gerard

## Do any offices have no employees?

In [3]:
#Your code here
cur.execute('''SELECT * FROM employees JOIN Offices using(officeCode) ''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df
#print(len(df))
print(len(df[df.officeCode.isnull()]))
#df[df.orderNumber.isnull()].head()

0

## Write 3 Questions of your own and answer them

In [ ]:
# Answers will vary

In [13]:
# Your code here
cur.execute('''SELECT * FROM customers JOIN payments using(customerNumber) GROUP BY contactLastName, contactFirstName''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit,checkNumber,paymentDate,amount
0,249,Amica Models & Co.,Accorti,Paolo,011-4988555,Via Monte Bianco 34,,Torino,,10100,Italy,1401,113000.00,NE404084,2004-09-04,48298.99
1,187,"AV Stores, Co.",Ashworth,Rachel,(171) 555-1555,Fauntleroy Circus,,Manchester,,EC2 5NT,UK,1501,136800.00,KL124726,2003-03-27,48425.69
2,204,Online Mini Collectables,Barajas,Miguel,6175557555,7635 Spinnaker Dr.,,Brickhaven,MA,58339,USA,1188,68700.00,IS150005,2004-09-24,4424.40
3,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00,PE176846,2004-11-27,48355.87
4,240,giftsbymail.co.uk,Bennett,Helen,(198) 555-8888,Garden House,Crowther Way 23,Cowes,Isle of Wight,PO31 7PJ,UK,1501,93900.00,JO719695,2004-03-28,24995.61
5,144,"Volvo Model Replicas, Co",Berglund,Christina,0921-12 3555,Berguvsvägen 8,,Luleå,,S-958 22,Sweden,1504,53100.00,LA685678,2003-04-09,7674.94
6,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,MA302151,2004-11-28,34638.14
7,172,"La Corne D'abondance, Co.",Bertrand,Marie,(1) 42.34.2555,"265, boulevard Charonne",,Paris,,75012,France,1337,84300.00,EH208589,2003-04-20,33383.14
8,324,"Stylish Desk Decors, Co.",Brown,Ann,(171) 555-0297,35 King George,,London,,WX3 6FW,UK,1501,77000.00,HB150714,2003-11-23,37455.77
9,321,Corporate Gift Ideas Co.,Brown,Julie,6505551386,7734 Strong St.,,San Francisco,CA,94217,USA,1165,105000.00,LA556321,2005-03-15,46781.66
10,328,Tekni Collectables Inc.,Brown,William,2015559350,7476 Moss Rd.,,Newark,NJ,94019,USA,1323,43000.00,NR631421,2004-05-30,31102.85
11,333,"Australian Gift Network, Co",Calaghan,Ben,61-7-3844-6555,31 Duncan St. West End,,South Brisbane,Queensland,4101,Australia,1611,51600.00,NF959653,2005-03-01,21432.31
12,381,Royale Belge,Cartrain,Pascale,(071) 23 67 2555,"Boulevard Tirou, 255",,Charleroi,,B-6000,Belgium,1401,23500.00,MS154481,2003-08-22,1128.20
13,189,"Clover Collections, Co.",Cassidy,Dean,+353 1862 1555,25 Maiden Lane,Floor No. 4,Dublin,,2,Ireland,1504,69400.00,NM916675,2004-03-01,32538.74
14,339,"Classic Gift Ideas, Inc",Cervantes,Francisca,2155554695,782 First Street,,Philadelphia,PA,71270,USA,1188,81100.00,DA98827,2003-11-28,34606.28
15,347,"Men 'R' US Retailers, Ltd.",Chandler,Brian,2155554369,6047 Douglas Av.,,Los Angeles,CA,91003,USA,1166,57700.00,LG808674,2003-10-24,20452.50
16,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00,MO743231,2004-04-30,1679.92
17,209,Mini Caravy,Citeaux,Frédérique,88.60.1555,"24, place Kléber",,Strasbourg,,67000,France,1370,53800.00,PH785937,2004-05-04,36069.26
18,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00,CO645196,2003-12-10,35505.63
19,385,Cruz & Sons Co.,Cruz,Arnold,+63 2 555 3587,15 McCallum Street,NatWest Center #13-03,Makati City,,1227 MM,Philippines,1621,81500.00,EK785462,2003-03-09,51001.22
20,250,Lyon Souveniers,Da Silva,Daniel,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,,Paris,,75508,France,1337,68100.00,HN114306,2003-07-18,23419.47
21,201,"UK Collectables, Ltd.",Devon,Elizabeth,(171) 555-2282,"12, Berkeley Gardens Blvd",,Liverpool,,WX1 6LT,UK,1501,92700.00,OO846801,2004-06-15,37258.94
22,314,Petit Auto,Dewey,Catherine,(02) 5554 67,Rue Joseph-Bens 532,,Bruxelles,,B-1180,Belgium,1401,79900.00,MD809704,2004-03-03,16901.38
23,415,"Bavarian Collectables Imports, Co.",Donnermeyer,Michael,+49 89 61 08 9555,Hansastr. 15,,Munich,,80686,Germany,1504,77000.00,ER54537,2004-09-28,31310.09
24,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,NR27552,2004-03-10,44894.74
25,344,CAF Imports,Fernandez,Jesus,+34 913 728 555,Merchants House,27-30 Merchant's Quay,Madrid,,28023,Spain,1702,59600.00,NJ906924,2004-04-02,15322.93
26,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00,FN155234,2004-05-14,6276.60
27,233,Québec Home Shopping Network,Fresnière,Jean,(514) 555-8054,43 rue St. Laurent,,Montréal,Québec,H1J 1C3,Canada,1286,48700.00,JG981190,2003-11-18,16909.84
28,141,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",,Madrid,,28034,Spain,1370,227600.00,NU627706,2004-05-17,26155.91
29,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286,76400.00,OH367219,2004-11-16,44400.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,145,Danish Wholesale Imports,Petersen,Jytte,31 12 3555,Vinbæltet 34,,Kobenhavn,,1734,Denmark,1401,83400.00,JJ246391,2003-02-20,53959.21
69,259,"Toms Spezialitäten, Ltd",Pfalzheim,Henriette,0221-5554327,Mehrheimerstr. 369,,Köln,,50739,Germany,1504,120400.00,GB361972,2003-12-07,27988.47
70,382,Salzburg Collectables,Pipps,Georg,6562-9555,Geislweg 14,,Salzburg,,5020,Austria,1401,71700.00,PH29054,2004-11-27,42813.83
71,171,Daedalus Designs Imports,Rancé,Martine,20.16.1555,"184, chaussée de Tournai",,Lille,,59000,France,1370,82900.00,IL104425,2003-11-22,42783.81
72,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,Italy,1401,34800.00,PC688499,2003-10-27,17746.26
73,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,Spain,1702,65700.00,JH546765,2003-11-29,47513.19
74,242,Alpha Cognac,Roulet,Annette,61.77.6555,1 rue Alsace-Lorraine,,Toulouse,,31000,France,1370,61100.00,KI744716,2003-07-21,14232.70
75,278,Rovelli Gifts,Rovelli,Giovanni,035-640555,Via Ludovico il Moro 22,,Bergamo,,24100,Italy,1401,119600.00,NI983021,2003-11-24,37723.79
76,216,Enaco Distributors,Saavedra,Eduardo,(93) 203 4555,"Rambla de Cataluña, 23",,Barcelona,,08022,Spain,1702,60300.00,MM342086,2003-12-14,40473.86
77,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00,JB117768,2003-03-20,25833.14
78,146,"Saveley & Henriot, Co.",Saveley,Mary,78.32.5555,"2, rue du Commerce",,Lyon,,69004,France,1337,123900.00,LJ160635,2003-12-10,39712.10
79,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00,OM314933,2004-12-18,1676.14
80,398,"Tokyo Collectables, Ltd",Shimamura,Akiko,+81 3 3584 0555,2-2-8 Roppongi,,Minato-ku,Tokyo,106-0032,Japan,1621,94400.00,KB54275,2004-11-29,48927.64
81,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00,PO860906,2004-01-31,7310.42
82,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00,MN89921,2004-12-31,52166.00
83,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00,OO606861,2003-06-13,57131.92
84,334,Suominen Souveniers,Suominen,Kalle,+358 9 8045 555,Software Engineering Center,SEC Oy,Espoo,,FIN-02271,Finland,1501,98800.00,LF737277,2004-05-22,28394.54
85,202,Canadian Gift Exchange Network,Tamuri,Yoshi,(604) 555-3392,1900 Oak St.,,Vancouver,BC,V3F 2K1,Canada,1323,90300.00,IQ627690,2004-11-08,33594.58
86,198,Auto-Moto Classics Inc.,Taylor,Leslie,6175558428,16780 Pompton St.,,Brickhaven,MA,58339,USA,1216,23000.00,IS946883,2004-09-21,5858.56
87,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00,PT550181,2004-02-29,12573.28
88,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00,PB951268,2004-02-13,36070.47
89,239,Collectable Mini Designs Co.,Thompson,Valarie,7605558146,361 Furth Circle,,San Diego,CA,91217,USA,1166,105000.00,NQ865547,2004-03-15,80375.24
90,256,Auto Associés & Cie.,Tonini,Daniel,30.59.8555,"67, avenue de l'Europe",,Versailles,,78000,France,1370,77900.00,HE84936,2004-10-22,53116.99
91,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,,Cambridge,MA,51247,USA,1188,43400.00,IG462397,2004-03-29,20355.24
92,166,Handji Gifts& Co,Victorino,Wendy,+65 224 1555,106 Linden Road Sandown,2nd Floor,Singapore,,069045,Singapore,1612,97900.00,LA318629,2004-02-28,22474.17
93,362,Gifts4AllAges.com,Yoshido,Juri,6175559555,8616 Spinnaker Dr.,,Boston,MA,51003,USA,1216,41900.00,OG208861,2004-09-21,15059.76
94,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,,Nashua,NH,62005,USA,1216,114200.00,PN238558,2003-12-05,55425.77
95,151,Muscle Machine Inc,Young,Jeff,2125557413,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,1286,138500.00,KI884577,2004-12-14,39964.63
96,205,Toys4GrownUps.com,Young,Julie,6265557265,78934 Hillside Dr.,,Pasadena,CA,90003,USA,1166,90700.00,NM739638,2005-02-06,39580.60
97,219,Boards & Toys Co.,Young,Mary,3105552373,4097 Douglas Av.,,Glendale,CA,92561,USA,1166,11000.00,BR941480,2003-10-18,4465.85

In [19]:
# Your code here
cur.execute('''SELECT * FROM products JOIN orderdetails using(Productcode) GROUP BY productLine ORDER BY quantityOrdered DESC''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,orderNumber,quantityOrdered,priceEach,orderLineNumber
0,S50_1514,1962 City of Detroit Streetcar,Trains,1:50,Classic Metal Creations,This streetcar is a joy to see. It has 99 sepa...,1645,37.49,58.58,10413,51,53.31,4
1,S72_3212,Pont Yacht,Ships,1:72,Unimax Art Galleries,Measures 38 inches Long x 33 3/4 inches High. ...,414,33.30,54.60,10414,47,54.60,9
2,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15,10424,46,85.98,1
3,S72_1253,Boeing X-32A JSF,Planes,1:72,Motor City Art Classics,"10"" Wingspan with retractable landing gears.Co...",4857,32.77,49.66,10415,42,43.20,3
4,S50_4713,2002 Yamaha YZR M1,Motorcycles,1:50,Autoart Studio Design,"Features rotating wheels , working kick stand....",600,34.17,81.36,10418,40,72.41,7
5,S50_1341,1930 Buick Marquette Phaeton,Vintage Cars,1:50,Studio M Art Models,"Features opening trunk, working steering system",7062,27.06,43.64,10416,37,39.71,8
6,S50_1392,Diamond T620 Semi-Skirted Tanker,Trucks and Buses,1:50,Highway 66 Mini Classics,This limited edition model is licensed and per...,1016,68.29,115.75,10425,18,94.92,2

In [ ]:
# Your code here

## Level Up: Display the names of each product each employee has sold.

In [10]:
# Your code here
cur.execute('''SELECT * FROM employees e
                        JOIN customers c
                        on e.employeeNumber = c.salesRepemployeeNumber 
                        JOIN orders o
                        USING (customerNumber)
                        JOIN ''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,customerNumber,customerName,...,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep,487,Signal Collectibles Ltd.,...,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00
1,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep,475,West Coast Collectables Co.,...,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00
2,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep,495,Diecast Collectables,...,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00
3,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep,462,FunGiftIdeas.com,...,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00
4,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep,456,Microscale Inc.,...,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00
5,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep,486,Motor Mint Distributors Inc.,...,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00
6,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep,406,Auto Canal+ Petit,...,Dominique,(1) 47.55.6555,"25, rue Lauriston",,Paris,,75016,France,1337,95000.00
7,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep,256,Auto Associés & Cie.,...,Daniel,30.59.8555,"67, avenue de l'Europe",,Versailles,,78000,France,1370,77900.00
8,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep,473,Frau da Collezione,...,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,Italy,1401,34800.00
9,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep,489,"Double Decker Gift Stores, Ltd",...,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00
10,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep,448,Scandinavian Gift Ideas,...,Martha,0695-34 6555,Åkergatan 24,,Bräcke,,S-844 67,Sweden,1504,116400.00
11,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep,471,"Australian Collectables, Ltd",...,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00
12,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep,496,Kelly's Gift Shop,...,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00
13,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep,398,"Tokyo Collectables, Ltd",...,Akiko,+81 3 3584 0555,2-2-8 Roppongi,,Minato-ku,Tokyo,106-0032,Japan,1621,94400.00
14,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep,484,"Iberia Gift Imports, Corp.",...,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,Spain,1702,65700.00

In [7]:
cur.execute('''SELECT * FROM customers
                        ''')
df = pd.DataFrame(cur.fetchall())
df.columns = [i[0] for i in cur.description]
df

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800.00
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200.00
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00
5,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,,Warszawa,,01-012,Poland,,0.00
7,128,"Blauer See Auto, Co.",Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,,Frankfurt,,60528,Germany,1504,59700.00
8,129,Mini Wheels Co.,Murphy,Julie,6505555787,5557 North Pendale Street,,San Francisco,CA,94217,USA,1165,64600.00
9,131,Land of Toys Inc.,Lee,Kwai,2125557818,897 Long Airport Avenue,,NYC,NY,10022,USA,1323,114900.00
10,141,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",,Madrid,,28034,Spain,1370,227600.00
11,144,"Volvo Model Replicas, Co",Berglund,Christina,0921-12 3555,Berguvsvägen 8,,Luleå,,S-958 22,Sweden,1504,53100.00
12,145,Danish Wholesale Imports,Petersen,Jytte,31 12 3555,Vinbæltet 34,,Kobenhavn,,1734,Denmark,1401,83400.00
13,146,"Saveley & Henriot, Co.",Saveley,Mary,78.32.5555,"2, rue du Commerce",,Lyon,,69004,France,1337,123900.00
14,148,"Dragon Souveniers, Ltd.",Natividad,Eric,+65 221 7555,Bronz Sok.,Bronz Apt. 3/6 Tesvikiye,Singapore,,079903,Singapore,1621,103800.00
15,151,Muscle Machine Inc,Young,Jeff,2125557413,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,1286,138500.00
16,157,Diecast Classics Inc.,Leong,Kelvin,2155551555,7586 Pompton St.,,Allentown,PA,70267,USA,1216,100600.00
17,161,Technics Stores Inc.,Hashimoto,Juri,6505556809,9408 Furth Circle,,Burlingame,CA,94217,USA,1165,84600.00
18,166,Handji Gifts& Co,Victorino,Wendy,+65 224 1555,106 Linden Road Sandown,2nd Floor,Singapore,,069045,Singapore,1612,97900.00
19,167,Herkku Gifts,Oeztan,Veysel,+47 2267 3215,Brehmen St. 121,PR 334 Sentrum,Bergen,,N 5804,Norway,1504,96800.00
20,168,American Souvenirs Inc,Franco,Keith,2035557845,149 Spinnaker Dr.,Suite 101,New Haven,CT,97823,USA,1286,0.00
21,169,Porto Imports Co.,de Castro,Isabel,(1) 356-5555,Estrada da saúde n. 58,,Lisboa,,1756,Portugal,,0.00
22,171,Daedalus Designs Imports,Rancé,Martine,20.16.1555,"184, chaussée de Tournai",,Lille,,59000,France,1370,82900.00
23,172,"La Corne D'abondance, Co.",Bertrand,Marie,(1) 42.34.2555,"265, boulevard Charonne",,Paris,,75012,France,1337,84300.00
24,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,,Cambridge,MA,51247,USA,1188,43400.00
25,175,Gift Depot Inc.,King,Julie,2035552570,25593 South Bay Ln.,,Bridgewater,CT,97562,USA,1323,84300.00
26,177,Osaka Souveniers Co.,Kentary,Mory,+81 06 6342 5555,1-6-20 Dojima,,Kita-ku,Osaka,530-0003,Japan,1621,81200.00
27,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286,76400.00
28,186,"Toys of Finland, Co.",Karttunen,Matti,90-224 8555,Keskuskatu 45,,Helsinki,,21240,Finland,1501,96500.00
29,187,"AV Stores, Co.",Ashworth,Rachel,(171) 555-1555,Fauntleroy Circus,,Manchester,,EC2 5NT,UK,1501,136800.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,386,L'ordine Souveniers,Moroni,Maurizio,0522-556555,Strada Provinciale 124,,Reggio Emilia,,42100,Italy,1401,121400.00
93,398,"Tokyo Collectables, Ltd",Shimamura,Akiko,+81 3 3584 0555,2-2-8 Roppongi,,Minato-ku,Tokyo,106-0032,Japan,1621,94400.00
94,406,Auto Canal+ Petit,Perrier,Dominique,(1) 47.55.6555,"25, rue Lauriston",,Paris,,75016,France,1337,95000.00
95,409,Stuttgart Collectable Exchange,Müller,Rita,0711-555361,Adenauerallee 900,,Stuttgart,,70563,Germany,,0.00
96,412,"Extreme Desk Decorations, Ltd",McRoy,Sarah,04 499 9555,101 Lambton Quay,Level 11,Wellington,,,New Zealand,1612,86800.00
97,415,"Bavarian Collectables Imports, Co.",Donnermeyer,Michael,+49 89 61 08 9555,Hansastr. 15,,Munich,,80686,Germany,1504,77000.00
98,424,Classic Legends Inc.,Hernandez,Maria,2125558493,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,1286,67500.00
99,443,"Feuer Online Stores, Inc",Feuer,Alexander,0342-555176,Heerstr. 22,,Leipzig,,04179,Germany,,0.00
100,447,Gift Ideas Corp.,Lewis,Dan,2035554407,2440 Pompton St.,,Glendale,CT,97561,USA,1323,49700.00
101,448,Scandinavian Gift Ideas,Larsson,Martha,0695-34 6555,Åkergatan 24,,Bräcke,,S-844 67,Sweden,1504,116400.00
102,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,,San Jose,CA,94217,USA,1165,77600.00
103,452,Mini Auto Werke,Mendel,Roland,7675-3555,Kirchgasse 6,,Graz,,8010,Austria,1401,45300.00
104,455,Super Scale Inc.,Murphy,Leslie,2035559545,567 North Pendale Street,,New Haven,CT,97823,USA,1286,95400.00
105,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00
106,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00
107,459,Warburg Exchange,Ottlieb,Sven,0241-039123,Walserweg 21,,Aachen,,52066,Germany,,0.00
108,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00
109,465,"Anton Designs, Ltd.",Anton,Carmen,+34 913 728555,"c/ Gobelas, 19-1 Urb. La Florida",,Madrid,,28023,Spain,,0.00
110,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00
111,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,Italy,1401,34800.00
112,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00
113,477,Mit Vergnügen & Co.,Moos,Hanna,0621-08555,Forsterstr. 57,,Mannheim,,68306,Germany,,0.00
114,480,"Kremlin Collectables, Co.",Semenov,Alexander,+7 812 293 0521,2 Pobedy Square,,Saint Petersburg,,196143,Russia,,0.00
115,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,,Herzlia,,47625,Israel,,0.00
116,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,Spain,1702,65700.00
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00

## Level Up: Display the Number of Products each Employee Has sold

In [ ]:
#Your code here

## Summary

Congrats! You now know how to use Join statements, along with leveraging your foreign keys knowledge!